"""Derive the anonymous NeurIPS-workshop submission from `writeup_workshop.tex`.

Two things have to be true of the submitted PDF and are not true of the working
draft: it must be in the venue's style file, and it must be double-blind. Both
are mechanical, so they are done here rather than in a second hand-maintained
`.tex`. That matters for this project specifically -- every defect the August
audit turned up had the same shape, a number in prose drifting from the artifact
that produced it, and a forked paper source is exactly that failure waiting to
happen. Edit `writeup_workshop.tex`; re-run this; never edit the output.

    python scripts/make_submission_tex.py
    python scripts/make_submission_tex.py --final     # camera-ready, de-anonymized

Anonymisation is `neurips_2024.sty`'s own: with no package option the style is in
submission mode and prints "Anonymous Author(s)" in place of whatever `\\author`
contains, so the author block does not have to be deleted -- but everything that
leaks identity through a side channel does, and the style cannot see those:

  - the GitHub URL, twice. This is the one that actually matters. `Abraham-y` in
    the path de-anonymises instantly and a reviewer does not have to be looking.
  - the Author Contributions appendix, which names A.Y. and A.R. and describes
    who did what.
  - any acknowledgments naming the course, the institution, or a person.

What deliberately survives: the `asingh15/qwen-sft-countdown-defaultproj`
checkpoint identifier. It is a public model ID that the setup cannot be described
without, it is cited the way any public artifact is cited, and stripping it would
make the paper unreproducible to protect an anonymity it does not actually
threaten. Reviewers see third-party model IDs in blind submissions constantly.

The script fails loudly rather than silently shipping a de-anonymised PDF: after
rewriting, it greps the result for every identity marker it knows about and exits
non-zero if one survives. A blown anonymisation is a desk reject, so this check
is the point of the script as much as the rewriting is.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

SRC = os.path.join(_ROOT, "archive", "papers", "writeup_workshop.tex")
OUT = os.path.join(_ROOT, "writeup_workshop_submission.tex")

# Anything matching these must not appear in an anonymous build. Checked after
# the rewrite, not trusted to have been handled by it.
IDENTITY_PATTERNS = [
    r"Abraham",
    r"Anagha",
    r"Yeung",
    r"Ramaswamy",
    r"ayeung",
    r"stanford",
    r"CS\s?224\s?R",
    r"Anikait",
    r"github\.com/Abraham-y",
    # The repo has been renamed once already (cs224r-project ->
    # reader-writer-probe-rl). Match the repo NAME too, not just the owner path:
    # a rename that the URL replacement above missed would otherwise sail through
    # this check and de-anonymise the submission.
    r"reader-writer-probe-rl",
    r"cs224r-project",
    r"A\.Y\.",
    r"A\.R\.",
]

# The preamble the draft uses fights the style file: `geometry` overrides the
# venue's margins, and `natbib` is loaded by neurips_2024 itself, so loading it
# again with different options is a package-option clash.
NEURIPS_PREAMBLE = r"""\documentclass{article}

% Anonymous submission: no package option puts neurips_2024 in submission mode,
% which prints "Anonymous Author(s)" regardless of \author. Use [final] for
% camera-ready. Generated by scripts/make_submission_tex.py -- do not edit.
\usepackage@@NEURIPS_OPT@@

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{hyperref}
\usepackage{url}
\usepackage{booktabs}
\usepackage{amsmath,amssymb}
\usepackage{amsfonts}
\usepackage{microtype}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{enumitem}
\usepackage[section]{placeins}

\title{Reading vs.\ Writing a Near-Oracle Internal Verifier:\\
How RL Design Determines Whether a Correctness Probe Is Safe}

@@AUTHOR_BLOCK@@

\begin{document}
\maketitle
"""

ANON_AUTHOR = r"""\author{%
  Anonymous Author(s) \\
  Affiliation \\
  Address \\
  \texttt{email} \\
}"""

FINAL_AUTHOR = r"""\author{%
  Abraham Yeung \\
  Stanford University \\
  \texttt{ayeung16@stanford.edu} \\
  \And
  Anagha Ramaswamy \\
  Stanford University \\
}"""


def strip_preamble(src: str) -> str:
    """Return everything after \\maketitle -- the body we keep verbatim."""
    i = src.index(r"\maketitle")
    return src[i + len(r"\maketitle"):]


def anonymise(body: str) -> str:
    # The GitHub URL, both occurrences. An anonymised-artifact placeholder is the
    # convention; a bare removal would make the reproducibility appendix read as
    # though no code exists, which is worse than saying it is withheld for review.
    body = body.replace(
        r"\url{https://github.com/Abraham-y/reader-writer-probe-rl}",
        r"\texttt{[code repository withheld for anonymous review]}",
    )
    body = body.replace(
        r"Code at \texttt{[code repository withheld for anonymous review]}.",
        r"Code will be released on acceptance; it is withheld here only for anonymity.",
    )

    # The Author Contributions appendix names both authors and splits the work
    # between them. Delete the whole section, not just the names.
    body = re.sub(
        r"\\section\{Author Contributions\}\\label\{app:contrib\}.*?(?=\\section\{)",
        "",
        body,
        flags=re.S,
    )
    # ...and the \thanks pointer to it, wherever it survived.
    body = re.sub(r"Author contribution breakdown in Appendix~\\ref\{app:contrib\}\.\s*", "", body)

    # Acknowledgments, if the draft ever grows one (the .md has one; the .tex
    # does not today). Handled now so it cannot leak in later unnoticed.
    body = re.sub(
        r"\\section\*?\{Acknowledge?ments?\}.*?(?=\\section|\\end\{document\})",
        "",
        body,
        flags=re.S | re.I,
    )
    return body


def check_anonymous(text: str) -> list[str]:
    hits = []
    for pat in IDENTITY_PATTERNS:
        for m in re.finditer(pat, text, re.I):
            line = text.count("\n", 0, m.start()) + 1
            hits.append(f"line {line}: {pat!r} -> {text[max(0, m.start()-40):m.end()+40]!r}")
    return hits


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--final", action="store_true",
                    help="camera-ready: de-anonymise and pass [final] to the style")
    ap.add_argument("--check", metavar="TEX",
                    help="do not generate anything: just run the anonymity scan over "
                         "an existing .tex (use this on the file you actually submit)")
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    # The submission that goes to JUDGe (writeup_judge.tex) was cut down by hand
    # rather than produced by this generator, so nothing was scanning it. A
    # generator that only vets its own output leaves the actual artifact ungated,
    # which is the same shape of gap as A8 in docs/CODE_AUDIT.md. --check closes it.
    if args.check:
        text = open(args.check).read()
        hits = check_anonymous(text)
        print(f"anonymity scan of {os.path.relpath(args.check, _ROOT)} "
              f"against {len(IDENTITY_PATTERNS)} patterns")
        if hits:
            print("\nFAILED -- these survived:", file=sys.stderr)
            for h in hits:
                print("  " + h, file=sys.stderr)
            sys.exit(1)
        print("clean")
        return

    src = open(args.src).read()
    body = strip_preamble(src)
    if not args.final:
        body = anonymise(body)

    # Token replacement rather than %-formatting: the preamble is full of LaTeX
    # comments, and every one of those `%` is a format specifier to Python.
    preamble = (NEURIPS_PREAMBLE
                .replace("@@NEURIPS_OPT@@",
                         "[final]{neurips_2024}" if args.final else "{neurips_2024}")
                .replace("@@AUTHOR_BLOCK@@",
                         FINAL_AUTHOR if args.final else ANON_AUTHOR))

    out_text = preamble + body
    with open(args.out, "w") as f:
        f.write(out_text)

    print(f"wrote {os.path.relpath(args.out, _ROOT)}"
          f"  ({'CAMERA-READY, de-anonymised' if args.final else 'ANONYMOUS'})")

    if not args.final:
        hits = check_anonymous(out_text)
        if hits:
            print("\nANONYMISATION FAILED -- these survived:", file=sys.stderr)
            for h in hits:
                print("  " + h, file=sys.stderr)
            sys.exit(1)
        print(f"anonymisation check: clean against {len(IDENTITY_PATTERNS)} patterns")


if __name__ == "__main__":
    main()
